In [1]:
from numpy import *

# EigenValues & EigenVectors

### Power method
To find the largest eigenvalue of a matrix A we can use the power method.

In [4]:
n = 9
h = 1./(n - 1)

x = linspace(0, 1, n)

a = -ones((n-1,))
b = 2 * ones((n,))
A = diag(a, -1) + diag(b, 0) + diag(a, 1)
A /= h**2
print(A)

[[128. -64.   0.   0.   0.   0.   0.   0.   0.]
 [-64. 128. -64.   0.   0.   0.   0.   0.   0.]
 [  0. -64. 128. -64.   0.   0.   0.   0.   0.]
 [  0.   0. -64. 128. -64.   0.   0.   0.   0.]
 [  0.   0.   0. -64. 128. -64.   0.   0.   0.]
 [  0.   0.   0.   0. -64. 128. -64.   0.   0.]
 [  0.   0.   0.   0.   0. -64. 128. -64.   0.]
 [  0.   0.   0.   0.   0.   0. -64. 128. -64.]
 [  0.   0.   0.   0.   0.   0.   0. -64. 128.]]


In [5]:
z0 = zeros_like(x)